package com.app.synapse.data.model

import android.os.Parcelable
import com.google.firebase.firestore.DocumentId
import com.google.firebase.firestore.ServerTimestamp
import kotlinx.parcelize.Parcelize
import java.util.Date

/**
 * Represents a chat channel.
 *
 * @param id The unique ID of the channel (auto-generated by Firestore or set manually).
 * @param name The name of the channel.
 * @param description A brief description of the channel (optional).
 * @param lastMessageText The text of the last message sent in this channel (optional, for previews).
 * @param lastMessageTimestamp Timestamp of the last message (optional, for sorting/previews).
 * @param memberCount Number of members in the channel (optional, requires managing members).
 * @param createdAt Timestamp of when the channel was created.
 */
@Parcelize // If you need to pass Channel objects via Intents
data class Channel(
    @DocumentId // Firestore will automatically populate this with the document ID
    var id: String = "",
    val name: String = "",
    val description: String? = null,
    val lastMessageText: String? = null,
    @ServerTimestamp
    val lastMessageTimestamp: Date? = null,
    // val memberIds: List<String> = emptyList(), // If you manage explicit members
    // val memberCount: Int = 0,
    @ServerTimestamp
    val createdAt: Date? = null,
    val createdBy: String? = null // Optional: UID of the user who created the channel
) : Parcelable {
    // No-argument constructor for Firestore deserialization
    constructor() : this("", "", null, null, null, null, null)
}
